# The variable BRANCH_NAME_VAR is replaced at build time with the branch name
baseURL: https://storage.cloud.google.com/papercut-website-static-content/BRANCH_NAME_VAR/
uglyURLs: true

buildExpired: true
buildDrafts: true
buildFuture: true

deployment:
  targets:
  - name: GCS
    URL: "gs://papercut-website-static-content?prefix=BRANCH_NAME_VAR/"

params:
  featureFlags:
    exampleFeatureFlag: true
